apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

# ✅ common transformer
commonLabels:
  app: demo
  managed-by: kustomize

# ✅ name transformer
namePrefix: base-

# ✅ namespace transformer
namespace: default
