apiVersion: apps/v1
kind: Deployment
metadata:
  name: base-app   # IMPORTANT: must match transformed name
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: app
          image: nginx:1.22
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
